# Generated by Django 4.2.30 on 2026-06-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_google_oauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('email_otp_hash', models.CharField(max_length=255)),
                ('phone_otp_hash', models.CharField(max_length=255)),
                ('pending_name', models.CharField(max_length=255)),
                ('pending_dob', models.CharField(max_length=20)),
                ('pending_pw_hash', models.CharField(max_length=255)),
                ('attempts', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otp_verifications',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
